version: '3.8'

services:
  # MinIO service for object storage
  minio:
    image: minio/minio:latest
    container_name: restaurant-minio
    ports:
      - "9000:9000"     # API port
      - "9001:9001"     # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - restaurant-network
  
  # Create bucket on startup (optional, but helpful)
  createbuckets:
    image: minio/mc
    container_name: restaurant-minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add restaurantminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb restaurantminio/restaurant-images;
      /usr/bin/mc policy set public restaurantminio/restaurant-images;
      exit 0;
      "
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  minio-data:
    driver: local